export const disData = () => {
const data = [
    {
        city: 'Dhaka',
        upazilas: ['Dhamrai', 'Dohar', 'Keraniganj', 'Nawabganj', 'Savar'],
    },
    {
        city: 'Bagerhat',
        upazilas: [
            'Kachua',
            'Chitalmari',
            'Fakirhat',
            'Bagerhat Sadar',
            'Mongla',
            'Morrelganj',
            'Mollahat',
            'Rampal',
            'Sharankhola',
        ],
    },
    {
        city: 'Bandarban',
        upazilas: [
            'Alikadam',
            'Thanchi',
            'Naikhongchhari',
            'Bandarban Sadar',
            'Ruma',
            'Rowangchhari',
            'Lama',
        ],
    },
    {
        city: 'Barguna',
        upazilas: [
            'Barguna Sadar',
            'Amtali',
            'Taltali',
            'Patharghata',
            'Betagi',
            'Bamna',
        ],
    },
    {
        city: 'Barishal',
        upazilas: [
            'Agailjhara',
            'Bakerganj',
            'Babuganj',
            'Banaripara',
            'Gournadi',
            'Hijla',
            'Barishal Sadar',
            'Mehendiganj',
            'Muladi',
            'Wazirpur',
        ],
    },
    {
        city: 'Bhola',
        upazilas: [
            'Char Fasson',
            'Tazumuddin',
            'Daulatkhan',
            'Borhanuddin',
            'Bhola Sadar',
            'Monpura',
            'Lalmohan',
        ],
    },
    {
        city: 'Bogura',
        upazilas: [
            'Adamdighi',
            'Bogura Sadar',
            'Dhunat',
            'Dupchanchia',
            'Gabtali',
            'Kahaloo',
            'Nandigram',
            'Sariakandi',
            'Sherpur',
            'Shibganj',
            'Sonatala',
            'Shajahanpur',
        ],
    },
    {
        city: 'Brahmanbaria',
        upazilas: [
            'Ashuganj',
            'Akhaura',
            'Kasba',
            'Nabinagar',
            'Nasirnagar',
            'Bancharampur',
            'Brahmanbaria Sadar',
            'Sarail',
            'Bijoynagar',
        ],
    },
    {
        city: 'Chandpur',
        upazilas: [
            'Chandpur Sadar',
            'Hajiganj',
            'Kachua',
            'Faridganj',
            'Matlab Uttar',
            'Matlab Dakshin',
            'Haimchar',
            'Shahrasti',
        ],
    },
    {
        city: 'Chattogram',
        upazilas: [
            'Anwara',
            'Karnaphuli',
            'Chandanaish',
            'Patiya',
            'Fatikchhari',
            'Banshkhali',
            'Boalkhali',
            'Mirsharai',
            'Raozan',
            'Rangunia',
            'Lohagara',
            'Sandwip',
            'Satkania',
            'Sitakunda',
            'Hathazari',
        ],
    },
    {
        city: 'Chuadanga',
        upazilas: ['Alamdanga', 'Chuadanga Sadar', 'Jibannagar', 'Damurhuda'],
    },
    {
        city: "Cox's Bazar",
        upazilas: [
            'Ukhiya',
            "Cox's Bazar Sadar",
            'Kutubdia',
            'Chakaria',
            'Teknaf',
            'Pekua',
            'Maheshkhali',
            'Ramu',
            'Eidgaon',
        ],
    },
    {
        city: 'Cumilla',
        upazilas: [
            'Barura',
            'Chandina',
            'Daudkandi',
            'Laksam',
            'Brahmanpara',
            'Burichang',
            'Chauddagram',
            'Debidwar',
            'Homna',
            'Muradnagar',
            'Nangalkot',
            'Meghna',
            'Titas',
            'Monohorgonj',
            'Cumilla Adarsha Sadar',
            'Cumilla Sadar Dakshin',
            'Lalmai',
        ],
    },
    {
        city: 'Dinajpur',
        upazilas: [
            'Birampur',
            'Birganj',
            'Bochaganj',
            'Fulbari',
            'Chirirbandar',
            'Ghoraghat',
            'Hakimpur',
            'Kaharole',
            'Khansama',
            'Dinajpur Sadar',
            'Nawabganj',
            'Parbatipur',
            'Biral',
        ],
    },
    {
        city: 'Faridpur',
        upazilas: [
            'Faridpur Sadar',
            'Boalmari',
            'Alfadanga',
            'Madhukhali',
            'Nagarkanda',
            'Saltha',
            'Bhanga',
            'Char Bhadrasan',
            'Sadarpur',
        ],
    },
    {
        city: 'Feni',
        upazilas: [
            'Feni Sadar',
            'Daganbhuiyan',
            'Sonagazi',
            'Chhagalnaiya',
            'Parshuram',
            'Phulgazi',
        ],
    },
    {
        city: 'Gaibandha',
        upazilas: [
            'Gaibandha Sadar',
            'Fulchhari',
            'Gobindaganj',
            'Palashbari',
            'Sadullapur',
            'Saghata',
            'Sundarganj',
        ],
    },
    {
        city: 'Gazipur',
        upazilas: [
            'Gazipur Sadar',
            'Kaliakair',
            'Kaliganj',
            'Kapasia',
            'Sreepur',
        ],
    },
    {
        city: 'Gopalganj',
        upazilas: [
            'Gopalganj Sadar',
            'Muksudpur',
            'Kashiani',
            'Kotalipara',
            'Tungipara',
        ],
    },
    {
        city: 'Habiganj',
        upazilas: [
            'Habiganj Sadar',
            'Nabiganj',
            'Bahubal',
            'Chunarughat',
            'Shayestaganj',
            'Madhabpur',
            'Lakhai',
            'Baniachang',
            'Ajmiriganj',
        ],
    },
    {
        city: 'Jamalpur',
        upazilas: [
            'Jamalpur Sadar',
            'Bakshiganj',
            'Dewanganj',
            'Islampur',
            'Madarganj',
            'Melandaha',
            'Sarishabari',
        ],
    },
    {
        city: 'Jashore',
        upazilas: [
            'Abhaynagar',
            'Keshabpur',
            'Chowgacha',
            'Jhikargacha',
            'Bagherpara',
            'Monirampur',
            'Jashore Sadar',
            'Sharsha',
        ],
    },
    {
        city: 'Jhalokathi',
        upazilas: ['Kathalia', 'Jhalokathi Sadar', 'Nalitabari', 'Rajapur'],
    },
    {
        city: 'Jhenaidah',
        upazilas: [
            'Kaliganj',
            'Kotchandpur',
            'Jhenaidah Sadar',
            'Maheshpur',
            'Shailkupa',
            'Harinakunda',
        ],
    },
    {
        city: 'Joypurhat',
        upazilas: [
            'Panchbibi',
            'Kalai',
            'Khetlal',
            'Akkelpur',
            'Joypurhat Sadar',
        ],
    },
    {
        city: 'Khagrachhari',
        upazilas: [
            'Khagrachhari Sadar',
            'Dighinala',
            'Panchhari',
            'Mahalchhari',
            'Matiranga',
            'Manikchhari',
            'Ramgarh',
            'Lakshmichhari',
            'Guimara',
        ],
    },
    {
        city: 'Kishoreganj',
        upazilas: [
            'Kishoreganj Sadar',
            'Austagram',
            'Itna',
            'Karimganj',
            'Katiadi',
            'Kuliarchar',
            'Tarail',
            'Nikli',
            'Pakundia',
            'Bajitpur',
            'Mithamain',
            'Hossainpur',
            'Bhairab',
        ],
    },
    {
        city: 'Kurigram',
        upazilas: [
            'Ulipur',
            'Kurigram Sadar',
            'Char Rajibpur',
            'Chilmari',
            'Nageshwari',
            'Phulbari',
            'Bhurungamari',
            'Rajarhat',
            'Roumari',
        ],
    },
    {
        city: 'Kushtia',
        upazilas: [
            'Kumarkhali',
            'Kushtia Sadar',
            'Khoksa',
            'Daulatpur',
            'Bheramara',
            'Mirpur',
        ],
    },
    {
        city: 'Lakshmipur',
        upazilas: [
            'Kamalnagar',
            'Ramganj',
            'Ramgati',
            'Raipur',
            'Lakshmipur Sadar',
        ],
    },
    {
        city: 'Lalmonirhat',
        upazilas: [
            'Aditmari',
            'Kaliganj',
            'Patgram',
            'Lalmonirhat Sadar',
            'Hatibandha',
        ],
    },
    {
        city: 'Madaripur',
        upazilas: ['Madaripur Sadar', 'Shibchar', 'Rajoir', 'Kalkini', 'Dasar'],
    },
    {
        city: 'Magura',
        upazilas: ['Magura Sadar', 'Mohammadpur', 'Shalikha', 'Sreepur'],
    },
    {
        city: 'Manikganj',
        upazilas: [
            'Manikganj Sadar',
            'Shibalaya',
            'Ghior',
            'Daulatpur',
            'Saturia',
            'Singair',
            'Harirampur',
        ],
    },
    {
        city: 'Meherpur',
        upazilas: ['Gangni', 'Meherpur Sadar', 'Mujibnagar'],
    },
    {
        city: 'Moulvibazar',
        upazilas: [
            'Moulvibazar Sadar',
            'Rajnagar',
            'Sreemangal',
            'Kamalganj',
            'Kulaura',
            'Juri',
            'Barlekha',
        ],
    },
    {
        city: 'Munshiganj',
        upazilas: [
            'Munshiganj Sadar',
            'Sreenagar',
            'Lohajang',
            'Sirajdikhan',
            'Tongibari',
            'Gazaria',
        ],
    },
    {
        city: 'Mymensingh',
        upazilas: [
            'Mymensingh Sadar',
            'Trishal',
            'Gauripur',
            'Muktagacha',
            'Phulpur',
            'Tarakanda',
            'Haluaghat',
            'Bhaluka',
            'Phulbaria',
            'Gafargaon',
            'Ishwarganj',
            'Nandail',
            'Dhobaura',
        ],
    },
    {
        city: 'Naogaon',
        upazilas: [
            'Patnitala',
            'Dhamoirhat',
            'Mohadevpur',
            'Porsha',
            'Sapahar',
            'Badalgachhi',
            'Manda',
            'Niamatpur',
            'Atrai',
            'Raninagar',
            'Naogaon Sadar',
        ],
    },
    {
        city: 'Narail',
        upazilas: ['Kalia', 'Narail Sadar', 'Lohagara'],
    },
    {
        city: 'Narayanganj',
        upazilas: [
            'Narayanganj Sadar',
            'Bandar',
            'Sonargaon',
            'Araihazar',
            'Rupganj',
        ],
    },
    {
        city: 'Narsingdi',
        upazilas: [
            'Narsingdi Sadar',
            'Belabo',
            'Monohardi',
            'Shibpur',
            'Raipura',
            'Palash',
        ],
    },
    {
        city: 'Natore',
        upazilas: [
            'Natore Sadar',
            'Bagatipara',
            'Baraigram',
            'Gurudaspur',
            'Lalpur',
            'Singra',
            'Naldanga',
        ],
    },
    {
        city: 'Netrakona',
        upazilas: [
            'Atpara',
            'Barhatta',
            'Durgapur',
            'Khaliajuri',
            'Kalmakanda',
            'Kendua',
            'Madan',
            'Mohanganj',
            'Netrakona Sadar',
            'Purbadhala',
        ],
    },
    {
        city: 'Nilphamari',
        upazilas: [
            'Nilphamari Sadar',
            'Domar',
            'Dimla',
            'Jaldhaka',
            'Kishoreganj',
            'Saidpur',
        ],
    },
    {
        city: 'Noakhali',
        upazilas: [
            'Noakhali Sadar',
            'Begumganj',
            'Chatkhil',
            'Companiganj',
            'Hatiya',
            'Senbagh',
            'Subarnachar',
            'Sonaimuri',
            'Kabirhat',
        ],
    },
    {
        city: 'Pabna',
        upazilas: [
            'Atgharia',
            'Ishwardi',
            'Chatmohar',
            'Pabna Sadar',
            'Faridpur',
            'Bera',
            'Bhangura',
            'Santhia',
            'Sujanagar',
        ],
    },
    {
        city: 'Panchagarh',
        upazilas: ['Debiganj', 'Tetulia', 'Panchagarh Sadar', 'Atwari', 'Boda'],
    },
    {
        city: 'Patuakhali',
        upazilas: [
            'Patuakhali Sadar',
            'Bauphal',
            'Dashmina',
            'Galachipa',
            'Kalapara',
            'Mirzaganj',
            'Dumki',
            'Rangabali',
        ],
    },
    {
        city: 'Pirojpur',
        upazilas: [
            'Kaukhali',
            'Nazirpur',
            'Nesarabad (Swarupkati)',
            'Pirojpur Sadar',
            'Bhandaria',
            'Mathbaria',
            'Indurkani',
        ],
    },
    {
        city: 'Rajbari',
        upazilas: [
            'Rajbari Sadar',
            'Goalanda',
            'Pangsha',
            'Baliakandi',
            'Kalukhali',
        ],
    },
    {
        city: 'Rajshahi',
        upazilas: [
            'Bagha',
            'Puthia',
            'Paba',
            'Bagmara',
            'Tanore',
            'Mohanpur',
            'Charghat',
            'Godagari',
            'Durgapur',
        ],
    },
    {
        city: 'Rangamati',
        upazilas: [
            'Kaukhali',
            'Kaptai',
            'Jurachhari',
            'Naniarchar',
            'Barkal',
            'Baghaichhari',
            'Bilaichhari',
            'Rangamati Sadar',
            'Rajasthali',
            'Longadu',
        ],
    },
    {
        city: 'Rangpur',
        upazilas: [
            'Rangpur Sadar',
            'Badarganj',
            'Gangachara',
            'Kaunia',
            'Mithapukur',
            'Pirgachha',
            'Pirganj',
            'Taraganj',
        ],
    },
    {
        city: 'Satkhira',
        upazilas: [
            'Assasuni',
            'Kalaroa',
            'Kaliganj',
            'Tala',
            'Debhata',
            'Shyamnagar',
            'Satkhira Sadar',
        ],
    },
    {
        city: 'Shariatpur',
        upazilas: [
            'Shariatpur Sadar',
            'Zanjira',
            'Naria',
            'Bhedarganj',
            'Damudya',
            'Gosairhat',
        ],
    },
    {
        city: 'Sherpur',
        upazilas: [
            'Jhenaigati',
            'Nakla',
            'Nalitabari',
            'Sherpur Sadar',
            'Sreebardi',
        ],
    },
    {
        city: 'Sirajganj',
        upazilas: [
            'Ullapara',
            'Kazipur',
            'Kamarkhanda',
            'Chowhali',
            'Tarash',
            'Belkuchi',
            'Raiganj',
            'Shahjadpur',
            'Sirajganj Sadar',
        ],
    },
    {
        city: 'Sunamganj',
        upazilas: [
            'Sunamganj Sadar',
            'Bishwambharpur',
            'Tahirpur',
            'Madhyanagar',
            'Dharmapasha',
            'Jamalganj',
            'Shantiganj',
            'Dowarabazar',
            'Chhatak',
            'Jagannathpur',
            'Derai',
            'Shalla',
        ],
    },
    {
        city: 'Sylhet',
        upazilas: [
            'Sylhet Sadar',
            'Dakshin Surma',
            'Bishwanath',
            'Osmaninagar',
            'Balaganj',
            'Fenchuganj',
            'Golapganj',
            'Beanibazar',
            'Zakiganj',
            'Kanaighat',
            'Jaintiapur',
            'Gowainghat',
            'Companiganj',
        ],
    },
    {
        city: 'Tangail',
        upazilas: [
            'Tangail Sadar',
            'Kalihati',
            'Ghatail',
            'Basail',
            'Gopalpur',
            'Mirzapur',
            'Bhuapur',
            'Nagarpur',
            'Madhupur',
            'Sakhipur',
            'Delduar',
            'Dhanbari',
        ],
    },
    {
        city: 'Thakurgaon',
        upazilas: [
            'Thakurgaon Sadar',
            'Pirganj',
            'Baliadangi',
            'Ranisankail',
            'Haripur',
        ],
    },
    {
        city: 'Khulna',
        upazilas: [
            'Koyra',
            'Dumuria',
            'Terokhada',
            'Dacope',
            'Dighalia',
            'Paikgacha',
            'Phultala',
            'Batiaghata',
            'Rupsa',
        ],
    },
]

  return data
}
